### ISSUE TITLE
Supplementray Problems for 201-NYC-05 Question 5.12

### ISSUE THREAD

**Issue by Peter-Goudis** [yannlamontagne/cegep_linear_algebra_problems#24]
For part a) of this question, I believe the answer should be 5x-6y-2x+13=0 instead of 5x-6y-2x-13=0.

**Comment by Peter-Goudis** [comment]
![Screenshot_20221116_143530_Samsung Notes](https://user-images.githubusercontent.com/118390609/202278006-9796d73a-4b89-4a0c-8e85-cc328a586045.jpg)
Here's my work to show.

**Comment by yannlamontagne** [comment]
Fixed!  There was indeed a mistake!  Please come and collect your prize!
