### ISSUE TITLE
Supplementary Problems for 201-NYC-05 Question 4.2

### ISSUE THREAD

**Issue by QasimMughal21** [yannlamontagne/cegep_linear_algebra_problems#25]
I think that the answer for part d) of question 4.2 should be that the lines are the same and not just parallel. I came to this conclusion by determining that each line passes through the point used to define the equation of the other line. Since this is the case, and their direction vectors are multiples of one another, then I think both lines are identical.

**Comment by yannlamontagne** [comment]
Fixed!

Thanks Qasim!
