### ISSUE TITLE
Supplementary Problems for 201-NYC-05 Question 2.4.8

### ISSUE THREAD

**Issue by Patrickshaw04** [yannlamontagne/cegep_linear_algebra_problems#26]
The answer is incorrect for the following reasons:
1. The product of the matrices does not yield the desired matrix
2. Matrix 3 is not an elementary matrix

Solution:
Matrix 3 should be [1 0 0 | 1 1 0 | 0 0 1]

**Comment by yannlamontagne** [comment]
Hi Patrick,

You are correct.  Thanks for the correction.  Feel free to collect the reward in the next Winter semester.

Yann
