### ISSUE TITLE
Section 1.2 #27 b)

### ISSUE THREAD

**Issue by elizabeth-roberts** [yannlamontagne/cegep_linear_algebra_problems#29]
b) a & b when no solution -> a^2 -1=0 & ba-b can't =0

The pdf answers are a=-1 and b=all real numbers, but this is impossible because the matrix shows that b can't =0.

If b=0, ba-b=0 (0(anything)-0=0). It is impossible to create a row of zeros with a non-zero in the constant column this way, resulting in consistent solutions regardless of the value of a.

b can't equal all real numbers when it can't equal 0.

**Comment by yannlamontagne** [comment]
Fixed! Thank you!
