### ISSUE TITLE
1.2.13 b)

### ISSUE THREAD

**Issue by kyliexxu** [yannlamontagne/cegep_linear_algebra_problems#30]
For b), (x1, x2, x3) should be equal to (-3, 1, 4). I think that a retranscription mistake occurred because the matrix in reduced-row echelon form in section a) agrees with what I am saying. Also, when I plug in the values (-3, 1, 4) in the different equations, it gives me the right constants at the end. On the other hand, when I try with (-3, 2, 4), it does not give me the correct constants.

**Comment by yannlamontagne** [comment]
Fixed! Thank you!
