### ISSUE TITLE
Question 2.1.3 (GH)

### ISSUE THREAD

**Issue by MaxIngram05** [yannlamontagne/cegep_linear_algebra_problems#31]
Value of point a12 should be positive 1 rather than negative 1.

attached is a file with the solutions I have found to be correct
![IMG_0285](https://github.com/yannlamontagne/cegep_linear_algebra_problems/assets/160544897/380dface-4783-4943-8944-accc6271c47f)

**Comment by yannlamontagne** [comment]
Fixed! Thank you!
